### ISSUE TITLE
sound.retrieve downloads without filetype if the sound.name has no file extension

### ISSUE THREAD

**Issue by spookyUnknownUser** [MTG/freesound-python#9]
For instance
https://www.freesound.org/people/coldwellw/sounds/192452/
Would be downloaded however, without the wav extension.

I noticed under the apidocs that `sound `comes with a `type` parameter over [here ](https://www.freesound.org/docs/api/resources_apiv2.html#sound-instance). Could we not add type to the python library and then always save as `sound.name+sound.type`

Alternatively we could catch anything without an extension and simply add a .wav, since it seems like they are most often uploaded without extensions.

Thanks :)

**Comment by ffont** [comment]
You're right, we should add type when saving so that we make sure files are saved with an extension.
However I'd not set any type by default as it might be misleading.

The only problem is that the type field is only returned in queries if user requests it, so we should somehow enforce requesting type (which I don't like much) or find another solution.

Another option would be to directly save the file with the filename returned by Freesound which already includes a type. I'll investigate at some point.

For the moment what I recommend is that you get type field in your queries and then pass 'name' parameter to the retrieve method by manually constructing "%s.%s" % (sound.name, sound.type)

**Comment by spookyUnknownUser** [comment]
Yes. That should work!
